import pandas as pd
import pyodbc
import snowflake.connector
import argparse
import logging
import smtplib
import os
from datetime import datetime

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

print('Parsing the Arguments')
parser = argparse.ArgumentParser()
parser.add_argument('--SFUser', type=str)
parser.add_argument('--SFPwd', type=str)

args = parser.parse_args()


###################### sql server connection #################

try:
    print('Info: Connecting to sql Server')
    
    
    cnxn1 = pyodbc.connect('Driver={SQL Server};'
                      'Server=DC1DB32;'
                      'Database=NGSDW;'
                      'Trusted_Connection=yes;')
    cursor = cnxn1.cursor()
    cnxn2 = pyodbc.connect('Driver={SQL Server};'
                      'Server=FXDB1;'
                      'Database=Fulfillment;'
                      'Trusted_Connection=yes;')
    
    print("info: Established connection with Sql Server successfully.")
except:
  print("Error: Exception Occured while connecting to Sql Server")


###################### snowflake connection #################

try:
    print('Info: Connecting to snowflake Server')
    ctx = snowflake.connector.connect(
    user=''+args.SFUser+'',
    password=''+args.SFPwd+'',
    account='pitneybowes.us-east-1',)
    cs = ctx.cursor()
    cs.execute("USE warehouse FDR_GLOBAL_WH")
    cs.execute("Use database FDR_NGSDW_DB_PROD")

except:
    print("Error: Exception Occured while connecting to  snowflake")

def SqlServerCount():
    query1 =  """SELECT
             --SCHEMA_NAME(schema_id) AS [SchemaName],
             'FDRDW'AS [SchemaName],
             [Tables].name AS [TableName],
             SUM([Partitions].[rows]) AS [SQLRowCount]
             FROM sys.tables AS [Tables]
             JOIN sys.partitions AS [Partitions]
             ON [Tables].[object_id] = [Partitions].[object_id]
             AND [Partitions].index_id IN ( 0, 1 )
             WHERE [Tables].name IN ('ADDRESSDIM','CARRIEREVENT','CARRIERJUNKDIM','CUSTMANIFESTPACKAGE','DATEDIM','EXCEPTIONLABEL','FACILITYDIM','FEETYPEDIM','FULFILLPACKAGE','FULFILLSHIPMETHODDIM','FULFILLTRANSACTION','FULFILLTRANSACTIONINVOICEFEE','FWDCONTAINER','FWDPACKAGE','FWDPACKAGECYCLE','FWDPACKAGEEVENT','FWDPACKAGEINVOICE','FWDPACKAGEINVOICEFEE','FWDPACKAGERATING','FWDPACKAGERATINGFEE','FWDPACKAGESHIPMENT','FWDSHIPMENT','FWDTRACKING','FWDTRACKINGEVENT','FWDUSPSPACKAGE','FWDUSPSPACKAGEEVENT','ORGDIM','ORGHIERBRIDGE','PACKAGE','PACKAGECYCLE','PACKAGEEVENT','PACKAGEEVENTTOPIC','PACKAGEINVOICE','PACKAGESHIPMENT','PACKAGEWEIGHTDIM','PICKTICKET','PKGATTRIBUTEDIM','POSTALCLASSDIM','POSTALCODEDIM','RATECHARTDIM','REVPACKAGERATING','REVUSPSPACKAGE','SHADOWTRACKEVENT','SHADOWTRACKSHIPMENTTYPEDIM','SHIPZONEDIM','SLPACKAGEFEE','SORTDIM','STATEPROVINCEDIM','TIMEDIM','TIMEZONEDIM','TMSLOAD','TMSSHIPMENT','TRACKINGEVENTDIM','TRACKINGLABEL','TRACKINGLABELEVENT','USPSFACILITYDIM','USPSPRICINGCATEGORYDIM','ZONEMAPDIM')
             GROUP BY SCHEMA_NAME(schema_id), [Tables].name"""

    query2 =  """SELECT
            --SCHEMA_NAME(schema_id) AS [SchemaName],
            'FULFILLMENT'AS [SchemaName],
            [Tables].name AS [TableName],
            SUM([Partitions].[rows]) AS [SQLRowCount]
            FROM sys.tables AS [Tables]
            JOIN sys.partitions AS [Partitions]
            ON [Tables].[object_id] = [Partitions].[object_id]
            AND [Partitions].index_id IN ( 0, 1 )
            WHERE [Tables].name IN ('ARRIVAL','ARRIVALDOCUMENT','ARRIVALLOG','ASSEMBLY','ASSEMBLYDETAIL','BATCH','BATCHDETAIL','BATCHPICKLIST','BATCHPICKLISTSHIPMENT','CLIENT','CONTAINER','CONTAINERFUNCTION','CONTAINERTYPE','EMPLOYEE','FULFILLMENTMODEL','INVENTORY','INVENTORYARCHIVE','INVENTORYEXCEPTION','INVENTORYEXCEPTIONTYPE','INVENTORYISCLIENTARCHIVED','INVENTORYLOT','INVENTORYNOTE','INVENTORYREASON','INVENTORYSNAPSHOT','INVENTORYSNAPSHOTDETAIL','INVENTORYSNAPSHOTENDOFDAY','INVENTORYSNAPSHOTENDOFDAYDETAIL','INVENTORYVERIFY','MANIFEST','MANIFESTDETAIL','NOTE','PACKAGE','PICKINGEXCEPTION','PRODUCT','PRODUCTCUSTOMFIELD','PRODUCTMINIMUMINVENTORY','PROSHIP','RECEIVINGEXCEPTION','RECEIVINGEXCEPTIONLOG','RECEIVINGEXCEPTIONREASON','RETURN','RETURNDETAIL','SHIPMENT','SHIPMENTCUSTOMFIELD','SHIPMENTDETAIL','SHIPMENTDETAILPICKVERIFY','SHIPMENTDOCUMENT','SHIPMENTLOG','UPSEXPORT','WAREHOUSE','WAVE','WAVEATTRIBUTES','WAVEATTRIBUTESHIPMENTS','WORKORDER')
            GROUP BY SCHEMA_NAME(schema_id), [Tables].name"""
    df1 = pd.read_sql(query1,cnxn1)
    df2 = pd.read_sql(query2,cnxn2)
    sqlserverCount = df1.append(df2)
    sqlserverCount['TableName'] = sqlserverCount['TableName'].str.upper()
    return sqlserverCount


def SNowflakeCount(sqlserverCount):
    cs.execute("USE schema FDRDW")
    df3 = pd.read_sql_query("""SELECT 'FDRDW' AS SchemaName, 'ADDRESSDIM' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.ADDRESSDIM WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'CARRIEREVENT' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.CARRIEREVENT WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'CARRIERJUNKDIM' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.CARRIERJUNKDIM WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'CUSTMANIFESTPACKAGE' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.CUSTMANIFESTPACKAGE WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'DATEDIM' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.DATEDIM WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'EXCEPTIONLABEL' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.EXCEPTIONLABEL WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'FACILITYDIM' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.FACILITYDIM WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'FEETYPEDIM' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.FEETYPEDIM WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'FULFILLPACKAGE' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.FULFILLPACKAGE WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'FULFILLSHIPMETHODDIM' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.FULFILLSHIPMETHODDIM WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'FULFILLTRANSACTION' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.FULFILLTRANSACTION WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'FULFILLTRANSACTIONINVOICEFEE' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.FULFILLTRANSACTIONINVOICEFEE WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'FWDCONTAINER' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.FWDCONTAINER WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'FWDPACKAGE' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.FWDPACKAGE WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'FWDPACKAGECYCLE' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.FWDPACKAGECYCLE WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'FWDPACKAGEEVENT' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.FWDPACKAGEEVENT WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'FWDPACKAGEINVOICE' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.FWDPACKAGEINVOICE WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'FWDPACKAGEINVOICEFEE' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.FWDPACKAGEINVOICEFEE WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'FWDPACKAGERATING' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.FWDPACKAGERATING WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'FWDPACKAGERATINGFEE' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.FWDPACKAGERATINGFEE WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'FWDPACKAGESHIPMENT' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.FWDPACKAGESHIPMENT WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'FWDSHIPMENT' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.FWDSHIPMENT WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'FWDTRACKING' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.FWDTRACKING WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'FWDTRACKINGEVENT' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.FWDTRACKINGEVENT WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'FWDUSPSPACKAGE' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.FWDUSPSPACKAGE WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'FWDUSPSPACKAGEEVENT' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.FWDUSPSPACKAGEEVENT WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'ORGDIM' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.ORGDIM WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'ORGHIERBRIDGE' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.ORGHIERBRIDGE WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'PACKAGE' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.PACKAGE WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'PACKAGECYCLE' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.PACKAGECYCLE WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'PACKAGEEVENT' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.PACKAGEEVENT WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'PACKAGEEVENTTOPIC' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.PACKAGEEVENTTOPIC WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'PACKAGEINVOICE' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.PACKAGEINVOICE WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'PACKAGESHIPMENT' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.PACKAGESHIPMENT WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'PACKAGEWEIGHTDIM' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.PACKAGEWEIGHTDIM WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'PICKTICKET' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.PICKTICKET WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'PKGATTRIBUTEDIM' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.PKGATTRIBUTEDIM WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'POSTALCLASSDIM' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.POSTALCLASSDIM WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'POSTALCODEDIM' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.POSTALCODEDIM WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'RATECHARTDIM' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.RATECHARTDIM WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'REVPACKAGERATING' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.REVPACKAGERATING WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'REVUSPSPACKAGE' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.REVUSPSPACKAGE WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'SHADOWTRACKEVENT' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.SHADOWTRACKEVENT WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'SHADOWTRACKSHIPMENTTYPEDIM' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.SHADOWTRACKSHIPMENTTYPEDIM WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'SHIPZONEDIM' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.SHIPZONEDIM WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'SLPACKAGEFEE' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.SLPACKAGEFEE WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'SORTDIM' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.SORTDIM WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'STATEPROVINCEDIM' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.STATEPROVINCEDIM WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'TIMEDIM' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.TIMEDIM WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'TIMEZONEDIM' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.TIMEZONEDIM WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'TMSLOAD' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.TMSLOAD WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'TMSSHIPMENT' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.TMSSHIPMENT WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'TRACKINGEVENTDIM' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.TRACKINGEVENTDIM WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'TRACKINGLABEL' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.TRACKINGLABEL WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'TRACKINGLABELEVENT' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.TRACKINGLABELEVENT WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'USPSFACILITYDIM' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.USPSFACILITYDIM WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'USPSPRICINGCATEGORYDIM' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.USPSPRICINGCATEGORYDIM WHERE SFDelFlag<>1 UNION
                            SELECT 'FDRDW' AS SchemaName, 'ZONEMAPDIM' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FDRDW.ZONEMAPDIM WHERE SFDelFlag<>1""", ctx)
    cs.execute("USE schema FULFILLMENT")

    df4 = pd.read_sql_query("""SELECT 'FULFILLMENT' AS SchemaName, 'ARRIVAL' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.ARRIVAL WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'ARRIVALDOCUMENT' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.ARRIVALDOCUMENT WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'ARRIVALLOG' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.ARRIVALLOG WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'ASSEMBLY' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.ASSEMBLY WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'ASSEMBLYDETAIL' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.ASSEMBLYDETAIL WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'BATCH' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.BATCH WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'BATCHDETAIL' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.BATCHDETAIL WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'BATCHPICKLIST' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.BATCHPICKLIST WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'BATCHPICKLISTSHIPMENT' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.BATCHPICKLISTSHIPMENT WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'CLIENT' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.CLIENT WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'CONTAINER' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.CONTAINER WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'CONTAINERFUNCTION' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.CONTAINERFUNCTION WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'CONTAINERTYPE' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.CONTAINERTYPE WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'EMPLOYEE' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.EMPLOYEE WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'FULFILLMENTMODEL' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.FULFILLMENTMODEL WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'INVENTORY' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.INVENTORY WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'INVENTORYARCHIVE' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.INVENTORYARCHIVE WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'INVENTORYEXCEPTION' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.INVENTORYEXCEPTION WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'INVENTORYEXCEPTIONTYPE' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.INVENTORYEXCEPTIONTYPE WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'INVENTORYISCLIENTARCHIVED' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.INVENTORYISCLIENTARCHIVED WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'INVENTORYLOT' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.INVENTORYLOT WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'INVENTORYNOTE' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.INVENTORYNOTE WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'INVENTORYREASON' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.INVENTORYREASON WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'INVENTORYSNAPSHOT' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.INVENTORYSNAPSHOT WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'INVENTORYSNAPSHOTDETAIL' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.INVENTORYSNAPSHOTDETAIL WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'INVENTORYSNAPSHOTENDOFDAY' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.INVENTORYSNAPSHOTENDOFDAY WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'INVENTORYSNAPSHOTENDOFDAYDETAIL' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.INVENTORYSNAPSHOTENDOFDAYDETAIL WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'INVENTORYVERIFY' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.INVENTORYVERIFY WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'MANIFEST' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.MANIFEST WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'MANIFESTDETAIL' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.MANIFESTDETAIL WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'NOTE' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.NOTE WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'PACKAGE' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.PACKAGE WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'PICKINGEXCEPTION' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.PICKINGEXCEPTION WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'PRODUCT' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.PRODUCT WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'PRODUCTCUSTOMFIELD' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.PRODUCTCUSTOMFIELD WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'PRODUCTMINIMUMINVENTORY' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.PRODUCTMINIMUMINVENTORY WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'PROSHIP' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.PROSHIP WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'RECEIVINGEXCEPTION' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.RECEIVINGEXCEPTION WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'RECEIVINGEXCEPTIONLOG' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.RECEIVINGEXCEPTIONLOG WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'RECEIVINGEXCEPTIONREASON' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.RECEIVINGEXCEPTIONREASON WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'RETURN' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.RETURN WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'RETURNDETAIL' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.RETURNDETAIL WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'SHIPMENT' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.SHIPMENT WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'SHIPMENTCUSTOMFIELD' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.SHIPMENTCUSTOMFIELD WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'SHIPMENTDETAIL' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.SHIPMENTDETAIL WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'SHIPMENTDETAILPICKVERIFY' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.SHIPMENTDETAILPICKVERIFY WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'SHIPMENTDOCUMENT' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.SHIPMENTDOCUMENT WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'SHIPMENTLOG' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.SHIPMENTLOG WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'UPSEXPORT' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.UPSEXPORT WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'WAREHOUSE' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.WAREHOUSE WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'WAVE' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.WAVE WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'WAVEATTRIBUTES' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.WAVEATTRIBUTES WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'WAVEATTRIBUTESHIPMENTS' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.WAVEATTRIBUTESHIPMENTS WHERE SFDelFlag<>1 UNION
                       SELECT 'FULFILLMENT' AS SchemaName, 'WORKORDER' AS TableName, COUNT(*) AS SFROWCOUNT ,MAX(SFCREATETS) AS SFCREATETSMAX, MAX(SFUPDATETS) AS SFUPDATETSMAX  FROM FULFILLMENT.WORKORDER WHERE SFDelFlag<>1""", ctx)
    SFData = df3.append(df4)
    
    print(SFData.columns)

    merged_df = pd.merge(sqlserverCount, SFData, how='left', left_on=['SchemaName', 'TableName'],
                         right_on=['SCHEMANAME', 'TABLENAME'])

    merged_df['Count_Diff'] = merged_df['SQLRowCount'] - merged_df['SFROWCOUNT']
    
    Recon_df = merged_df[(merged_df['Count_Diff'] >= 500) | (merged_df['Count_Diff'] <= -500)]
    Recon_df.reset_index(drop=True, inplace=True)
    
    Recon_df.index += 1
    merged_df['CREATEDATE'] = datetime.now()
    file_name = f"HVR_Recon.csv"
    file_path = os.path.abspath(file_name)
    merged_df.to_csv(file_path, sep="|",index=False, header=False,columns=['SchemaName', 'TableName', 'SQLRowCount', 'SCHEMANAME', 'TABLENAME',
       'SFROWCOUNT', 'SFCREATETSMAX', 'SFUPDATETSMAX', 'Count_Diff',
       'CREATEDATE'])
    return Recon_df,file_path

def gethtmlReport(Recon_df):
    html = Recon_df.to_html()
    return html

def SendMail(html):
    From = "HVR-Alert@pb.com"
    To = "ankita.khaira@pb.com"
    msg = MIMEMultipart()
    msg['Subject'] = "ALERT - HVR Latency"
    msg['From'] = From
    msg['To'] = To
    text = "DBA Team,\n\n	Attached are the details of tables which reached latency threshold, please take necessary action."
    html = html
    part1 = MIMEText(text, 'plain')
    part2 = MIMEText(html, 'html')
    msg.attach(part1)
    msg.attach(part2)
    smtpObj = smtplib.SMTP('smtp-prod.corpdom1.com', 25)
    smtpObj.connect('smtp-prod.corpdom1.com', 25)
    smtpObj.ehlo()
    smtpObj.sendmail(From, To, msg.as_string())
    smtpObj.quit()
	
def insertdatatoSF(file_path):
    try:
        cs.execute("USE warehouse FDR_GLOBAL_WH")
        cs.execute("Use database DIA_ML_ANALYSIS_DB")
        cs.execute("USE schema FDRDWH")
        
        remove_files = pd.read_sql_query("""remove @HVRRECON;""", ctx)
        sql="put {} @HVRRECON;".format("file:///"+file_path)
        pull_detail_csv = pd.read_sql_query(sql, ctx)
        insert_data = pd.read_sql_query("""copy INTO "DIA_ML_ANALYSIS_DB"."FDRDWH"."HVR_RECON"
            from @HVRRECON
            file_format = (type = csv field_delimiter = '|' );""", ctx)

        print(' Inserted records into snowflake tables HVR_RECON')
        print("Completed Successfully")
        print("Deleting old records")
        Delete_olddata = pd.read_sql_query("""DELETE FROM "DIA_ML_ANALYSIS_DB"."FDRDWH"."HVR_RECON"
        WHERE CREATEDATE < dateadd(hour,-25,current_timestamp());""", ctx)
        print("Deleted old records")
    except:
        e = sys.exc_info()[0]

        print("Exception occured while inserting in Snowflake TABLE"+str(e) )
    finally:
        cs.close()
    return None
	


if __name__ == "__main__":
    print("info: Getting sql Server table Count")
    sqlserverCount = SqlServerCount()
    print("info: Getting snowflake count ")
    Recon_df,file_path = SNowflakeCount(sqlserverCount)
    print("info: Inserting data to Snowflake")
    insertdatatoSF(file_path)
    print("info: Generating html")
    html = gethtmlReport(Recon_df)
    print("info: Sending Mail")
    SendMail(html)
    print("Completed Successfully")
